### PR TITLE
Idl version

### PR DESCRIPTION
**Pull request by pyramation**

### CODE REVIEW

**Comment by pyramation** [comment]
when this is reviewed (and tested locally) will close https://github.com/CosmWasm/ts-codegen/issues/59

- [ ] reviewed
- [ ] local global CLI install test

**Comment by uint** [comment]
> @uint correct me if I'm wrong, but I don't think it breaks anything if this PR enables parsing of the new idl format to be treated like the current published version of ts-codegen (meaning w/o the named responses and keeping the <Thing>Response style for now til we close https://github.com/CosmWasm/ts-codegen/issues/61 )

I mean, if contract developers are willing to only partially migrate to the new way of generating APIs (while keeping the old `<Thing>Response.json` boilerplate), I imagine it should work out.

**Comment by uint** [comment]
This isn't a priority or anything, but in the future it would be nice to parse the `idl_version` as a semver value and make sure it satisfies the semver requirement of `^1.0.0` (or whatever the supported version is at the time). And just crash otherwise with `IDL version {idl_version} not supported`.

**Comment by pyramation** [comment]
great! thanks @uint 



> This isn't a priority or anything, but in the future it would be nice to parse the `idl_version` as a semver value and make sure it satisfies the semver requirement of `^1.0.0` (or whatever the supported version is at the time). And just crash otherwise with `IDL version {idl_version} not supported`.

I agree! awesome idea https://github.com/CosmWasm/ts-codegen/issues/62

**Pull request merged**
